import os

TEXTS_PATH = os.path.dirname(__file__) + '\\'
IMAGES_PATH = TEXTS_PATH.replace('\\texts', '') + '\\images\\'

GAME_NAME = 'TowerDefence'

MONSTER_IMAGE_SIZE_X = 32
MONSTER_IMAGE_SIZE_Y = 32

BLUE_MONSTER_SPEED = 2
BLUE_MONSTER_START_HEALTH = 140
BLUE_MONSTER_PRIZE = 20
BLUE_MONSTER_IMG = 'blue'

GREEN_MONSTER_SPEED = 2
GREEN_MONSTER_START_HEALTH = 120
GREEN_MONSTER_PRIZE = 10
GREEN_MONSTER_IMG = 'green'

RED_MONSTER_SPEED = 2
RED_MONSTER_START_HEALTH = 100
RED_MONSTER_PRIZE = 5
RED_MONSTER_IMG = 'red'

TOWER_IMAGE_SIZE_X = 26
TOWER_IMAGE_SIZE_Y = 37

BLUE_TOWER_STRENGTH = 20
BLUE_TOWER_AREA = 150
BLUE_TOWER_COST = 100
BLUE_TOWER_PERIOD = 200
BLUE_TOWER_IMAGE = 'tower_blue.png'
BLUE_TOWER_ICON_X = 1080
BLUE_TOWER_ICON_Y = 150

GREEN_TOWER_STRENGTH = 10
GREEN_TOWER_AREA = 130
GREEN_TOWER_COST = 25
GREEN_TOWER_PERIOD = 400
GREEN_TOWER_IMAGE = 'tower_green.png'
GREEN_TOWER_ICON_X = 1040
GREEN_TOWER_ICON_Y = 150

RED_TOWER_STRENGTH = 5
RED_TOWER_AREA = 110
RED_TOWER_COST = 15
RED_TOWER_PERIOD = 600
RED_TOWER_IMAGE = 'tower_red.png'
RED_TOWER_ICON_X = 1000
RED_TOWER_ICON_Y = 150

GAME_START_LIVES = 30
GAME_START_GOLD = 100

WAVE_LENGTH = 10

HELLO_MENU_SCREEN_SIZE = (800, 600)
HELLO_MENU_START_BUTTON_RECT = (320, 400, 173, 80)
HELLO_MENU_START_BUTTON_SIZE = (173, 80)
HELLO_MENU_START_BUTTON_IMAGE = 'start.png'
HELLO_MENU_EXIT_BUTTON_RECT = (320, 500, 173, 80)
HELLO_MENU_EXIT_BUTTON_SIZE = (173, 80)
HELLO_MENU_EXIT_BUTTON_IMAGE = 'exit.png'
HELLO_MENU_TITLE_SIZE = (699, 540)
HELLO_MENU_TITLE_BLIT = (100, 40)
HELLO_MENU_TITLE_TRANSFORM = (624, 152)
HELLO_MENU_BACKGROUND_BLIT = (0, 0)
HELLO_MENU_IMAGE = 'hello_menu_background.jpg'
HELLO_MENU_TITLE_IMAGE = 'tittle.png'
HELLO_MENU_GAME_OVER_IMAGE = 'game_over.png'

MAIN_WINDOW_SCREEN_SIZE = (1200, 600)
MAIN_WINDOW_PLAY_BUTTON_RECT = (1110, 520, 50, 46)
MAIN_WINDOW_PLAY_BUTTON_IMAGE = 'play.png'
MAIN_WINDOW_SIDE_MENU_IMAGE = 'wood.jpg'
MAIN_WINDOW_SIDE_MENU_BLIT = (900, 0)
MAIN_WINDOW_BACKGROUND_ORIGINAL_IMAGE = 'grass.png'
MAIN_WINDOW_BACKGROUND_ORIGINAL_IMAGE_BLIT = (0, -30)

MAIN_WINDOW_BACKGROUND_IMAGE = 'grass134.png'
MAIN_WINDOW_BACKGROUND_IMAGE_BLIT = (0, -30)

MAIN_WINDOW_ROAD_IMAGE = 'road.png'
MAIN_WINDOW_ROAD_BLIT = (0, -30)
MAIN_MENU_DESCRIPTION_NOTE_IMAGE = 'note.png'
MAIN_MENU_DESCRIPTION_NOTE_IMAGE_BLIT = (950, 215)
MAIN_MENU_STATS_NOTE_IMAGE = 'note1.png'
MAIN_MENU_STATS_NOTE_IMAGE_BLIT = (970, 5)
MAIN_WINDOW_STATS_FONT_SIZE = 27
MAIN_WINDOW_STATS_FONT_COLOR = (0, 0, 0)
MAIN_WINDOW_STATS_FONT_FAMILY = 'cinnamon-cake'
MAIN_WINDOW_STATS_LIVES = (995, 20)
MAIN_WINDOW_STATS_WAVES = (995, 50)
MAIN_WINDOW_STATS_GOLD = (995, 80)
MAIN_WINDOW_PLACES_FOR_TOWERS_COLOR = (163, 189, 0)
# MAIN_WINDOW_PLACES_FOR_TOWERS_COLOR = (255, 0, 0)
MAIN_WINDOW_REFRESH_PERIOD = 120
MAIN_WINDOWS_DESCRIPTION_FONT_FAMILY = 'cinnamon-cake'
MAIN_WINDOWS_DESCRIPTION_FONT_COLOR = (0, 0, 0)
MAIN_WINDOWS_DESCRIPTION_FONT_SIZE = 18
MAIN_WINDOWS_DESCRIPTION_X = 980
MAIN_WINDOWS_DESCRIPTION_Y = 250
